version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grocery_db
    ports: 
      - '5432:5432'
    volumes:
      - grocery-db:/var/lib/postgresql/data

  groceryapi:
    build:
      context: .
    environment:
      DB_SCHEMA: grocery_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
volumes:
  grocery-db: